name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 3.13.7
            tags: 3.13,3,3.13.7
          - version: 3.12.14
            tags: 3.12,3.12.14
          - version: 3.11.28
            tags: 3.11.28,3.11
          - version: 3.10.25
            tags: 3.10,3.10.25
          - version: 3.9.29
            tags: 3.9.29,3.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: prep
        run: |
          TAGS=""
          for tag in $(echo "${{ matrix.tags }}" | tr ',' '\n'); do
            TAGS+="ghcr.io/${{ github.repository_owner }}/rabbitmq-plugins:$tag\n"
          done
          echo -e "$TAGS" > tags.txt
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          cat tags.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            RABBITMQ_VERSION=${{ matrix.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.prep.outputs.tags }}
